# Generated by Django 5.2.4 on 2025-08-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabiliter', '0002_product_alter_user_role_historiquemodification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabiliter.company'),
        ),
    ]
