# Generated by Django 5.2.4 on 2025-08-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabiliter', '0003_alter_partner_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='pattern',
            new_name='patern',
        ),
        migrations.AddField(
            model_name='account',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabiliter.partner'),
        ),
    ]
