# Generated by Django 5.2.4 on 2025-08-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabiliter', '0006_alter_account_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcritureComptable',
        ),
    ]
