# Generated by Django 5.2.4 on 2025-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabiliter', '0007_delete_ecriturecomptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classe',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='compte',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sous_classe',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sous_compte',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
