# Generated by Django 5.2.4 on 2025-09-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabiliter', '0010_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='patern',
            new_name='partner',
        ),
    ]
